### ISSUE TITLE
Improve UI for Auth Policies and consider adding a Group property

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/dynamic-authorization-policy#39]
Arising from CMSi G5 project.
Awaiting detail – what would an admin want to do with the group beyond seeing it in the list of Auth Policies? Is it also a requirement to sort on the group? Filter by group?

There are some obvious UI improvements that might be as effective as adding a Group, and should be done anyway:
a) Allow the search to operate on any part of the policy name. At present it's a "starts with" search.
b) Add a page size control with the ability to show all records. It could allow page sizes 10, 25, 50, All

**Comment by JimKerslake** [comment]
Going to need to move the dev.webapp for dyn auth policies up to BS5 before I can see my own work on this...

**Comment by JimKerslake** [comment]
cloudscribe.DynamicPolicy.Storage.EFCore.Common  to 6.0.2
cloudscribe.DynamicPolicy.Storage.NoDb  to 6.0.1
cloudscribe.DynamicPolicy.Web.Mvc   to 6.0.1
cloudscribe.DynamicPolicy.Web.Views.Bootstrap5  to 6.0.1

(assuming you're upgraded to using the BS5 versions of views.)

**Comment by JimKerslake** [comment]
cloudscribe.DynamicPolicy.Storage.EFCore.MSSQL  to 6.0.2
cloudscribe.DynamicPolicy.Storage.EFCore.PostgreSql  to 6.0.2

also required to push up the transient dep's chain

**Comment by CrispinF** [comment]
This has been tested in several sites, and works nicely.
